package com.hand.pojo;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_id
     *
     * @mbggenerated
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_name
     *
     * @mbggenerated
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_gender
     *
     * @mbggenerated
     */
    private String empGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_age
     *
     * @mbggenerated
     */
    private Integer empAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_address
     *
     * @mbggenerated
     */
    private String empAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.comments
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_id
     *
     * @return the value of employee.emp_id
     *
     * @mbggenerated
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_id
     *
     * @param empId the value for employee.emp_id
     *
     * @mbggenerated
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_name
     *
     * @return the value of employee.emp_name
     *
     * @mbggenerated
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_name
     *
     * @param empName the value for employee.emp_name
     *
     * @mbggenerated
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_gender
     *
     * @return the value of employee.emp_gender
     *
     * @mbggenerated
     */
    public String getEmpGender() {
        return empGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_gender
     *
     * @param empGender the value for employee.emp_gender
     *
     * @mbggenerated
     */
    public void setEmpGender(String empGender) {
        this.empGender = empGender == null ? null : empGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_age
     *
     * @return the value of employee.emp_age
     *
     * @mbggenerated
     */
    public Integer getEmpAge() {
        return empAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_age
     *
     * @param empAge the value for employee.emp_age
     *
     * @mbggenerated
     */
    public void setEmpAge(Integer empAge) {
        this.empAge = empAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_address
     *
     * @return the value of employee.emp_address
     *
     * @mbggenerated
     */
    public String getEmpAddress() {
        return empAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_address
     *
     * @param empAddress the value for employee.emp_address
     *
     * @mbggenerated
     */
    public void setEmpAddress(String empAddress) {
        this.empAddress = empAddress == null ? null : empAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.comments
     *
     * @return the value of employee.comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.comments
     *
     * @param comments the value for employee.comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}